spring.application.name=TodoAPI


spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=apolat
spring.datasource.password=skaledman31
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=yoDMD1mZuFHYZWNkUGMjrVBlkju8mIv5nLV6rR62q17Skaledman
jwt.expiration=5600000
